name: Ruff

on: [pull_request, push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v2
        with:
          args: 'check'
      - uses: astral-sh/ruff-action@v2
        with:
          args: 'format --check'
